package com.acel.livela.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.acel.livela.bean.Anchor;

import com.acel.livela.db.AnchorDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig anchorDaoConfig;

    private final AnchorDao anchorDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        anchorDaoConfig = daoConfigMap.get(AnchorDao.class).clone();
        anchorDaoConfig.initIdentityScope(type);

        anchorDao = new AnchorDao(anchorDaoConfig, this);

        registerDao(Anchor.class, anchorDao);
    }
    
    public void clear() {
        anchorDaoConfig.clearIdentityScope();
    }

    public AnchorDao getAnchorDao() {
        return anchorDao;
    }

}
